# Generated by Django 4.1.3 on 2023-01-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranglar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=31)),
            ],
        ),
        migrations.RemoveField(
            model_name='gul',
            name='rangi',
        ),
        migrations.CreateModel(
            name='Barg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=31)),
                ('rangi', models.ManyToManyField(blank=True, to='core.ranglar')),
            ],
        ),
        migrations.AddField(
            model_name='gul',
            name='rangi',
            field=models.ManyToManyField(blank=True, to='core.ranglar'),
        ),
    ]
